// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2QDNwBFVS7f8eeOwGCzidL8FtaEHIrEU',
    appId: '1:592200229232:web:c6c5d7343bb6050ad3afb5',
    messagingSenderId: '592200229232',
    projectId: 'login-setup-78a50',
    authDomain: 'login-setup-78a50.firebaseapp.com',
    storageBucket: 'login-setup-78a50.appspot.com',
    measurementId: 'G-XK2CJNJQ22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfkIfn7kNZm28bVnQS2aDbD_XsVKB_Fcg',
    appId: '1:592200229232:android:858a86188755c324d3afb5',
    messagingSenderId: '592200229232',
    projectId: 'login-setup-78a50',
    storageBucket: 'login-setup-78a50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvqzWI-vQ13-qBSDhXnATfJPaotovqJq4',
    appId: '1:592200229232:ios:b1e376ac47353951d3afb5',
    messagingSenderId: '592200229232',
    projectId: 'login-setup-78a50',
    storageBucket: 'login-setup-78a50.appspot.com',
    androidClientId: '592200229232-lmgvombvdbmmodqvn4nflluqb46f6u3u.apps.googleusercontent.com',
    iosClientId: '592200229232-ecei9tdejcnjrf2msmpv35nl9tdsn7up.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvqzWI-vQ13-qBSDhXnATfJPaotovqJq4',
    appId: '1:592200229232:ios:b1e376ac47353951d3afb5',
    messagingSenderId: '592200229232',
    projectId: 'login-setup-78a50',
    storageBucket: 'login-setup-78a50.appspot.com',
    androidClientId: '592200229232-lmgvombvdbmmodqvn4nflluqb46f6u3u.apps.googleusercontent.com',
    iosClientId: '592200229232-ecei9tdejcnjrf2msmpv35nl9tdsn7up.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPage',
  );
}
